CREATE_TABLE T_TESTE_DDL
(
    CD_TESTE NUMBER(3)  NOT NULL,
    NM_TESTE VARCHAR2(30) NOT NULL,
    DS_TESTE VARCHAR2(300) NULL

);

ALTER TABLE T_TESTE_DDL
ADD CONSTRAINT PK_TESTE_DDL
PRIMARY KEY (CD_TESTE);

ALTER TABLE T_TESTE_DDL
ADD CONSTRAINT UN_TESTE_DDL_NONE
UNIQUE (NM_TESTE);

ALTER TABLE T_TESTE_DDL
ADD CONSTRAINT UN_TESTE_DDL_DESC
UNIQUE (NM_TESTE);

ALTER TABLE T_TESTE_DDL
ADD DS_EMAIL VARCHAR2(100);

ALTER TABLE T_TESTE_DDL
ADD (DS_OBS VARCHAR2(50) NOT NULL, DS_OBS2 VARCHAR2(50) NULL);

DESCRIBE T_TESTE_DDL;
DESC T_TESTE_DDL;

COMMENT ON TABLE T_TESTE_DDL IS 'Tabela utilizada para exemplo';
COMMENT ON COLUMN T_TESTE_DDL.DS_EMAIL IS 'Campo para Email'