CREATE TABLE T_RHSTU_MEDICO_CONTATO (
  cd_medico number(10) NOT NULL,
  id_contato number(3) NOT NULL,
  CONSTRAINT PK_MEDICO_CONTATO PRIMARY KEY (cd_medico),
  CONSTRAINT FK_MEDICO_CONTATO FOREIGN KEY (id_contato) REFERENCES TABELA_REFERENCIADA (COLUNA_REFERENCIADA)
);
